name: Build & Deploy Marp Presentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js for running Marp CLI
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Build: Convert README.md to index.html using Marp CLI
      - name: Convert README.md to index.html
        run: npx @marp-team/marp-cli@latest README.md -o index.html

      # Upload the built file as an artifact for GitHub Pages deployment
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: index.html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
